-- ============================================================
-- SEED INICIAL (VAZIO)
-- Populado com dados de demo nas migrations numeradas.
-- ============================================================
